import time
class Challan:
    def __init__(self, vehicle_id, amount, location, description):
        self.creation_time = time.time()
        self.vehicle_id = vehicle_id
        self.location = location
        self.amount = amount
        self.description = description
        self.settlement_time = 0.0
        self.status = "unsettled"
        self.due_time = self.creation_time + 60 * 60 * 24 * 90
        # id to be generated by cosmos db