class Transaction:
    def __init__(self, tag_id, type, amount, location, description):
        self.tag_id = tag_id
        self.type = type
        self.amount = amount
        self.location = location
        self.description = description
        # id to be generated by cosmos db itself