class User:
    def __init__(self, name, designation, email, password):
        self.name = name
        self.designation = designation
        self.email = email
        self.password = password
        # id to be generated by cosmos db itself