pipeline {
    agent any
    tools {
        terraform 'Terraform-Jenkins'
    }

    parameters {
        string(name: 'FUNCTION_NAME', defaultValue: 'Madhur-Test-Demo', description: 'Function App Name to deploy')
    }
    stages {
        stage('app deployment'){
            steps {
                script {
                    sh "cd 'Azure Functions'"
                    sh "func azure functionapp publish ${params.FUNCTION_NAME}"
                }
            }
        }
        stage('cleanup') {
            steps {
                cleanWs()
            }
        }
    }
post {
        always {
            echo 'Deployment finished.'
        }
    }
}
