pipeline {
    agent any
    tools {
        terraform 'Terraform-Jenkins'
    }

    parameters {
        string(name: 'FUNCTION_NAME', defaultValue: 'Madhur-Test-Demo', description: 'Function App Name to deploy')
    }
    stages {
        stage('Azure Login') {
            steps {
                script {
                    withCredentials([azureServicePrincipal(credentialsId:'AZURE_CRED',subscriptionIdVariable: 'AZURE_SUBSCRIPTION_ID',clientIdVariable: 'AZURE_CLIENT_ID',clientSecretVariable: 'AZURE_CLIENT_SECRET',tenantIdVariable: 'AZURE_TENANT_ID')]) { 
                    sh '''
                    az login --service-principal \
                        -u "$AZURE_CLIENT_ID" \
                        -p "$AZURE_CLIENT_SECRET" \
                        --tenant "$AZURE_TENANT_ID"
                    az account set --subscription "$AZURE_SUBSCRIPTION_ID"
                    '''
                    }
                }
            }
        }
        stage('app deployment'){
            steps {
                script {
                    sh "cd 'Azure Functions'"
                    sh "func init --worker-runtime python"
                    sh "func azure functionapp publish ${params.FUNCTION_NAME} --worker-runtime python --build remote"
                }
            }
        }
        stage('cleanup') {
            steps {
                cleanWs()
            }
        }
    }
post {
        always {
            echo 'Deployment finished.'
        }
    }
}
